version: '3.8'

services:
  db: 
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  postgres-data: